### ISSUE TITLE
r2_gazebo missing run depends

### ISSUE THREAD

**Issue by tfoote** [DLu/nasa_r2_simulator#1]
For the launch files r2_gazebo is missing a bunch of run dependencies. For main.launch I was missing these packages. 

ros-hydro-gazebo-ros ros-hydro-robot-state-publisher ros-hydro-controller-manager ros-hydro-gazebo-ros-control ros-hydro-r2-description

**Comment by DLu** [comment]
Is this something you just manually listed, or is there a particular way you test this?

**Comment by tfoote** [comment]
I tried running it and found errors. Fixed them, then retried.

**Comment by DLu** [comment]
Fixed with d9f756c9d3
